server:
  port: 8040
  shutdown: graceful
  tomcat:
    connection-timeout: 3s
    keep-alive-timeout: 20s
spring:
  application:
    name: usd-service
  lifecycle:
    timeout-per-shutdown-phase: 30s

cb_uri: "https://www.cbr-xml-daily.ru/daily_json.js"

external:
  zipkin-endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  loki-url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3
      produce: b3
      consume: b3
    export:
      enabled: true
      zipkin:
        endpoint: ${external.zipkin-endpoint}
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true