

services:
  keycloak-postgres:
    container_name: "keycloak-postgres"
    image: postgres:16.2
    networks:
      - tron-network
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    ports:
      - "5435:5435"
    restart: unless-stopped
    volumes:
      - ./docker-config/postgres/data:/var/lib/postgresql/data:rw
      - db:/var/lib/postgresql/data_keycloack
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: "keycloak"
    restart: unless-stopped
    networks:
      - tron-network
    command: start-dev --import-realm
    depends_on:
      - "keycloak-postgres"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=keycloak
      - KEYCLOAK_DATABASE_HOST=keycloak-postgres
    ports:
      - "8180:8080"
    volumes:
      - ./import:/opt/keycloak/data/import
  redis:
    image: "redis:7.2.4"
    container_name: "redis"
    restart: unless-stopped
    networks:
      - tron-network
    ports:
      - "6379:6379"
  postgres:
    image: "postgres:16.0"
    container_name: "postgres"
    restart: unless-stopped
    networks:
      - tron-network
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=tr_db
      - POSTGRES_USER=userbek
      - POSTGRES_PASSWORD=passwordbek
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U userbek -d tr_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 80s
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=4"
      - "-c"
      - "max_replication_slots=4"
  kafka:
    image: confluentinc/cp-kafka:7.5.2
    hostname: kafka
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    networks:
      - tron-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      CLUSTER_ID: X1oISRwqQ1yqeRlIjsegqQ
    volumes:
      - kafka-data:/var/lib/kafka/data

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.2
    hostname: schema-registry
    container_name: schema-registry
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    networks:
      - tron-network
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081


volumes:
  db:
    driver: local
  kafka-data:
    driver: local
  connect-data:
    driver: local

networks:
  tron-network: # Единая сеть для безопасного взаимодействия по именам сервисов
    driver: bridge


