global:
  scrape_interval: 2s
  scrape_timeout: 2s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8090']

  - job_name: 'wallet-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'wallet-service:8070' ]

  - job_name: 'banking-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'banking-service:8050' ]

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'notification-service:8100' ]

  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gateway-service:8080' ]

  - job_name: 'usd-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'usd-service:8040' ]
